# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designJuntar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_designJuntar(object):
    def setupUi(self, designJuntar):
        designJuntar.setObjectName("designJuntar")
        designJuntar.resize(541, 361)
        designJuntar.setStyleSheet("background-image: url(:/bgjuntar/images/texturaBg.jpg);")
        self.btnJuntar = QtWidgets.QPushButton(designJuntar)
        self.btnJuntar.setGeometry(QtCore.QRect(400, 320, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnJuntar.setFont(font)
        self.btnJuntar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnJuntar.setStyleSheet("background-color: rgba(255, 0, 0, 0.6);\n"
"color: rgb(255, 255, 255);")
        self.btnJuntar.setObjectName("btnJuntar")
        self.listDir = QtWidgets.QListWidget(designJuntar)
        self.listDir.setGeometry(QtCore.QRect(10, 80, 381, 231))
        self.listDir.setStyleSheet("background: transparent;\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.listDir.setObjectName("listDir")
        self.label_2 = QtWidgets.QLabel(designJuntar)
        self.label_2.setGeometry(QtCore.QRect(10, 320, 381, 31))
        self.label_2.setStyleSheet("background: transparent;\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.btnClear = QtWidgets.QPushButton(designJuntar)
        self.btnClear.setGeometry(QtCore.QRect(400, 180, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnClear.setFont(font)
        self.btnClear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClear.setStyleSheet("background-color: rgba(255, 0, 0, 0.6);\n"
"color: rgb(255, 255, 255);")
        self.btnClear.setObjectName("btnClear")
        self.label = QtWidgets.QLabel(designJuntar)
        self.label.setGeometry(QtCore.QRect(0, 0, 541, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setStyleSheet("background: transparent;\n"
"background-color: rgba(255, 0, 0, 0.5);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnArquivo = QtWidgets.QPushButton(designJuntar)
        self.btnArquivo.setGeometry(QtCore.QRect(400, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnArquivo.setFont(font)
        self.btnArquivo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnArquivo.setMouseTracking(False)
        self.btnArquivo.setStyleSheet("background-color: rgba(255, 0, 0, 0.6);\n"
"color: rgb(255, 255, 255);")
        self.btnArquivo.setObjectName("btnArquivo")
        self.btnDel = QtWidgets.QPushButton(designJuntar)
        self.btnDel.setGeometry(QtCore.QRect(400, 130, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnDel.setFont(font)
        self.btnDel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDel.setStyleSheet("background-color: rgba(255, 0, 0, 0.6);\n"
"color: rgb(255, 255, 255);")
        self.btnDel.setObjectName("btnDel")

        self.retranslateUi(designJuntar)
        QtCore.QMetaObject.connectSlotsByName(designJuntar)

    def retranslateUi(self, designJuntar):
        _translate = QtCore.QCoreApplication.translate
        designJuntar.setWindowTitle(_translate("designJuntar", "JuntarPDF"))
        self.btnJuntar.setText(_translate("designJuntar", "Juntar"))
        self.btnClear.setText(_translate("designJuntar", "Limpar"))
        self.label.setText(_translate("designJuntar", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">JuntarPDF </span></p></body></html>"))
        self.btnArquivo.setText(_translate("designJuntar", "Adicionar PDF"))
        self.btnDel.setText(_translate("designJuntar", "Deletar"))
from . import BgJuntar
