# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_designMenu(object):
    def setupUi(self, designMenu):
        designMenu.setObjectName("designMenu")
        designMenu.resize(540, 273)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(designMenu.sizePolicy().hasHeightForWidth())
        designMenu.setSizePolicy(sizePolicy)
        designMenu.setToolTip("")
        designMenu.setStyleSheet("background-image: url(:/bgmain/images/texturaBg.jpg);\n"
"")
        self.centralwidget = QtWidgets.QWidget(designMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 541, 71))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setStyleSheet("background: transparent;\n"
"background-color: rgba(0, 85, 127, 0.5);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnJuntarPdf = QtWidgets.QPushButton(self.centralwidget)
        self.btnJuntarPdf.setGeometry(QtCore.QRect(180, 90, 181, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnJuntarPdf.sizePolicy().hasHeightForWidth())
        self.btnJuntarPdf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnJuntarPdf.setFont(font)
        self.btnJuntarPdf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnJuntarPdf.setStyleSheet("background-color: rgba(255, 0, 0, 0.6);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btnJuntarPdf.setObjectName("btnJuntarPdf")
        self.btnImgToPdf = QtWidgets.QPushButton(self.centralwidget)
        self.btnImgToPdf.setGeometry(QtCore.QRect(180, 150, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnImgToPdf.setFont(font)
        self.btnImgToPdf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnImgToPdf.setStyleSheet("background-color: rgba(147, 6, 133, 0.6);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btnImgToPdf.setObjectName("btnImgToPdf")
        self.btnWordToPdf = QtWidgets.QPushButton(self.centralwidget)
        self.btnWordToPdf.setGeometry(QtCore.QRect(180, 210, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnWordToPdf.setFont(font)
        self.btnWordToPdf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWordToPdf.setStyleSheet("background-color: rgba(8, 12, 255, 0.6);\n"
"color: rgb(255, 255, 255);")
        self.btnWordToPdf.setObjectName("btnWordToPdf")
        designMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(designMenu)
        QtCore.QMetaObject.connectSlotsByName(designMenu)

    def retranslateUi(self, designMenu):
        _translate = QtCore.QCoreApplication.translate
        designMenu.setWindowTitle(_translate("designMenu", "PDF Manager"))
        self.label.setText(_translate("designMenu", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">PDF Manager</span></p></body></html>"))
        self.btnJuntarPdf.setText(_translate("designMenu", "JuntarPDF"))
        self.btnImgToPdf.setText(_translate("designMenu", "ImgToPDF"))
        self.btnWordToPdf.setText(_translate("designMenu", "WordToPDF"))
from . import BgMain
